// FI only. EN is read straight out of index.html.
window.FI = {
  "role": "Insinööri &amp; Perustaja",
  "now": "nyt",
  "freelance": "Freelancer",
  "fdf": "Puolustusvoimat",

  "nav.code": "Koodi",
  "nav.about": "Tietoa",
  "nav.cv": "CV",
  "nav.marketing": "Markkinointi",
  "nav.company": "Yritys",

  "graph.alt": "GitHub-kontribuutiokaavio käyttäjälle ishanmalu",
  "graph.label": "Kontribuutiot, viimeiset 6 kuukautta",
  "tag.private": "yksityinen repo",
  "tag.trial": "14 päivää ilmaiseksi",

  "code.tapli.1": "QR-tilaaminen ravintoloille, tuotannossa Suomessa ja päivittäisessä käytössä oikeilla tilauksilla. Asiakas skannaa koodin pöydässä, tilaa ja maksaa puhelimellaan, ja tilaus ilmestyy keittiön näytölle välittömästi — ei sovellusta ladattavaksi eikä henkilökuntaa pöytään.",
  "code.tapli.2": "Rakennan ja julkaisen tuotteen itse tekoälyavusteisesti: ravintolan hallintapaneeli, asiakkaan ruokalista, pöytätilaaminen ja keittiönäyttö. TypeScriptillä ja Reactilla Supabasen ja Cloudflaren päällä, ja Stripe Connect Expressillä ravintolat saavat maksut suoraan — ALV-kuitit ja hyvitykset hoituvat automaattisesti.",
  "code.tapli.3": "Kiinnostavimmat ongelmat ovat tuontipuolella: tekoäly lukee verkkosivun osoitteen, PDF:n tai valokuvan paperimenusta ja poimii jokaisen annoksen, hinnan ja kategorian sekunneissa, merkitsee kaikki 14 EU-allergeenia ja kääntää koko menun yli 20 kielelle yhdellä klikkauksella.",
  "code.perch.1": "Natiivi macOS-valikkorivin työkalu, joka yhdistää ikkunoiden asettelun, Alt-Tab-ikkunanvaihtajan, leikepöytähistorian, järjestelmän seurannan, levyn ja näytön puhdistuksen sekä näyttökohtaisen kirkkaudensäädön — ne asiat joihin aiemmin asensin kuusi eri sovellusta.",
  "code.perch.2": "Kirjoitettu Swiftillä ja rakennettu ilman Xcodea: SwiftPM, <code>lipo</code> universaaliin binääriin, ja itsetestit jotka elävät julkaistun binäärin sisällä. Allekirjoitettu, avointa lähdekoodia, dokumentaatiosivuston kanssa.",

  "about.1": "Olen Ishan — rakennan ohjelmistoja ja myyn niitä. Tällä hetkellä se tarkoittaa Taplia, SaaS-tuotetta QR-tilaamiseen suomalaisissa ravintoloissa. Perustin sen, rakennan sen ja pyöritän sitä päivittäin.",
  "about.2": "Reittini tänne ei ollut tavanomainen. Tein kolme vuotta lyhytvideosisältöä ja hoidin brändien somea, suoritin vuoden varusmiespalveluksen kersantiksi asti, ja myin kasvotusten yhdessä Suomen suurimmista kenttämyyntitoimistoista. Sen päälle insinöörityö rakentuu: otan yhä useimmat Taplin asiakkaat käyttöön itse, ja sieltä tuotesuunnitelma tulee.",
  "about.3": "Opiskelen tällä hetkellä tieto- ja viestintätekniikkaa Turun ammattikorkeakoulussa. Asun Helsingin, Vantaan ja Turun välillä.",

  "lang.en": "englanti — erinomainen",
  "lang.fi": "suomi — hyvä",
  "lang.hi": "hindi — äidinkieli",
  "lang.mwr": "marwari — äidinkieli",
  "lang.sv": "ruotsi — alkeet",

  "cv.skills": "Osaaminen",
  "sk.build.h": "Kehitys",
  "sk.build.p": "TypeScript, React, HTML/CSS ja SQL päivittäin; Python skripteihin ja datan käsittelyyn; jonkin verran Swiftiä.",
  "sk.ai.h": "Tekoälyavusteinen kehitys",
  "sk.ai.p": "Rakennan, suunnittelen ja julkaisen tuotanto-ominaisuuksia pääosin tekoälytyökalujen avulla ja tarkistan työn niiden kanssa.",
  "sk.plat.h": "Alustat ja työkalut",
  "sk.plat.p": "Supabase (PostgreSQL), Cloudflare Pages, Vercel, Stripe Connect, Git ja GitHub, Node.js, PostHog-analytiikka.",
  "sk.biz.h": "Liiketoiminta ja luova työ",
  "sk.biz.p": "B2B SaaS -myynti ja käyttöönotto, hinnoittelu, kasvumarkkinointi, lyhytvideosisältö, Premiere Pro, Photoshop, Illustrator, Canva.",

  "cv.experience": "Työkokemus",
  "cv.education": "Koulutus",
  "cv.certs": "Sertifikaatit",
  "cv.tapli": "Perustin ja johdan QR-tilaus- ja digitaalisen ruokalistan alustaa, joka on käytössä suomalaisravintoloissa. Vastaan myynnistä, hinnoittelusta, markkinoinnista ja tuotesuunnasta — ja rakennan tuotteen itse TypeScriptillä ja Reactilla Supabasen ja Cloudflaren päällä.",
  "cv.addnow": "Vastaan markkinoinnista ja sisällöstä tekoälypohjaisessa kontaktinhallintasovelluksessa. TikTok- ja Reels-käsikirjoitukset, karusellit, sisältökalenterit ja luova suunta.",
  "cv.helena": "Asiakaskohtaamisia ja tapahtumatyötä Helsingissä. Brändien edustamista suoraan kuluttajille.",
  "cv.clas": "Myymälätyö, esillepano ja tilausten käsittely Suomen ainoassa Clas Ohlsonin verkkokauppavarastossa. Club Clas -lähettiläänä seurasin ja kasvatin kanta-asiakasliittymisiä.",
  "cv.freelance": "Toteutin lyhytvideosisältöä brändeille alusta loppuun — käsikirjoitus, kuvaus, editointi ja tulosten analysointi — TikTokiin, Instagram Reelsiin, YouTube Shortsiin ja LinkedIniin, sekä podcast-editointia ja täyttä tuotantoa.",
  "cv.freelance.clients": "Asiakkaita mm. Moov Kids, Birkkalan Tila, Euro Scalers, The F-Company, Studio Manu ja Ome Energy by Hartwall.",
  "cv.fdf": "Vuosi varusmiespalvelusta Upinniemen merivoimien tukikohdassa. Aliupseerikurssi, sen jälkeen toimistoaliupseeri vastuussa yksikön dokumentaatiosta ja hallinnosta.",
  "cv.euro": "Lyhytvideoita ja somemarkkinointia. CapCut, Premiere Pro, Photoshop, Illustrator, Canva.",
  "cv.nordic": "Kasvokkaista myyntiä yhdessä Suomen suurimmista kenttämyyntitoimistoista. Vastaväitteiden käsittelyä ja asiakasviestintää.",

  "edu.turku.h": "Insinööri (AMK), tieto- ja viestintätekniikka",
  "edu.tampere.h": "Ohjelmistotekniikka, avoimen yliopiston väylä (20 op)",
  "edu.tampere.p": "Tampereen yliopisto",
  "edu.hs.h": "Ylioppilastutkinto",
  "edu.hs.p": "Vuosaaren lukio — opintoja Pythonista ja HTML:stä",

  "mk.intro": "Kolme vuotta lyhytvideosisältöä ja somea ennen kuin aloin rakentaa tuotteita — käsikirjoitusta, kuvausta, editointia ja lukujen lukemista jälkikäteen.",
  "mk.addnow": "Markkinointijohtaja tekoälypohjaisessa kontaktinhallintasovelluksessa. Tuotteen ominaisuuksien muuttamista sisällöksi jota ihmiset oikeasti katsovat: lyhyet koukut, build-in-public-videot ja opettavat julkaisut jotka tuovat latauksia.",
  "mk.free.h": "Freelance — sosiaalinen media ja videoeditointi",
  "mk.free.p1": "Kolme vuotta koko tuotantoketjua brändeille: käsikirjoitus, kuvaus, editointi ja lukujen lukeminen jälkikäteen. Lyhytvideoita TikTokiin, Instagram Reelsiin, YouTube Shortsiin ja LinkedIniin, sekä podcast-editointia ja tuotantoa alusta loppuun.",
  "mk.free.p2": "Ruoan, juoman, energian, maatalouden ja startupien parissa — kuusi asiakasta joiden yleisöillä ei ollut juuri mitään yhteistä, ja juuri se opetti eniten.",
  "mk.clients": "Editoinut näille",
  "mk.elisa": "Vastasin kansainvälisestä ja alueellisesta somesta (Twitter, Instagram, Twitch) livenä turnauksen aikana.",
  "mk.india": "Kuvasin ja editoin tapahtumasisältöä, mukaan lukien haastattelut Intian Suomen-suurlähettilään ja Maahanmuuttoviraston johtajan kanssa. Somemateriaalia ja verkkosivumuokkauksia.",
  "mk.slush.h": "Slush — media-alue",
  "mk.slush.p": "Tuin podcast-tiimejä, sisällöntekijöitä ja vieraita media-alueella sekä koordinoin haastatteluja. Aiemmin badge-tulostustuotantoa kahden päivän suuren volyymin työnkulussa.",
  "mk.coffee": "Valokuvausta ja videota someen Helsinki Coffee Festivalilla sekä Jäätelö- ja Suklaakarnevaaleilla.",

  "co.1": "SaaS-tuote QR-tilaamiseen ravintoloissa, tuotannossa Suomessa ja päivittäisessä käytössä oikeilla tilauksilla. Useimmat ravintolat ovat käytössä alle 30 minuutissa.",
  "co.2": "Asiakas skannaa tarran tai lasinalusen pöydässä, tai valitsee pöytänsä pohjapiirroksesta. Hän tilaa ja maksaa puhelimellaan — Apple Pay, Google Pay, MobilePay tai kortti — ja tilaus ilmestyy keittiön näytölle välittömästi, ohjattuna oikealle asemalle. Ei sovellusta eikä odottelua tarjoilijan katseen saamiseksi.",
  "co.3": "Käyttöönotto on se osa jota ravintolat pelkäävät. Liitä verkkosivusi osoite, lataa PDF tai valokuvaa paperimenusi, niin tekoäly poimii jokaisen tuotteen, hinnan ja kategorian sekunneissa. Tarkistat kaiken ennen tallennusta. Kaikki 14 EU-allergeenia merkitään, asiakkaat suodattavat reaaliajassa, ja yksi klikkaus kääntää koko menun yli 20 kielelle.",
  "co.4": "Menun lisäksi: päivän tarjoukset jotka vanhenevat itsestään, tilausten seuranta reaaliajassa, skannaus- ja hakuanalytiikka CSV-vientinä, brändinmukainen ulkoasu esikatselulla, ja tekoälyn luonnostelemat vastaukset Google-arvosteluihin. Toimii myös ruokarekoille, festivaalikojuille ja hotelleille — huonepalvelu, baari ja spa saman QR-koodin takana.",
  "co.5": "Perustin Taplin ja pyöritän sitä päivittäin. Myynti, markkinointi, kasvu, hinnoittelu, ja yhdessä CTO:n kanssa päätökset siitä mitä rakennamme ja mitä jätämme tekemättä. Ravintolat pyytävät sinulta kaikkea, ja suurin osa työstä on sen selvittämistä mikä siitä oikeasti liikuttaa liiketoimintaa. Otan yhä useimmat asiakkaat käyttöön itse, ja sieltä tuotesuunnitelma tulee."
};
