// FI only. EN is read straight out of index.html.
window.FI = {
  "role": "Perustaja &amp; insinööri",
  "now": "nyt",

  "nav.code": "Koodi",
  "nav.about": "Tietoa",
  "nav.cv": "CV",
  "nav.marketing": "Markkinointi",
  "nav.company": "Yritys",

  "graph.label": "Kontribuutiot",
  "tag.private": "yksityinen repo",
  "tag.trial": "14 päivää ilmaiseksi",

  "code.tapli.1": "QR-tilaaminen ravintoloille, tuotannossa Suomessa ja päivittäisessä käytössä oikeilla tilauksilla. Asiakas skannaa koodin pöydässä, tilaa ja maksaa puhelimellaan, ja tilaus ilmestyy keittiön näytölle välittömästi — ei sovellusta ladattavaksi eikä odottelua tarjoilijan katseen saamiseksi.",
  "code.tapli.2": "Rakennan ja julkaisen tuotteen itse tekoälyavusteisesti: ravintolan hallintapaneeli, asiakkaan ruokalista, pöytätilaaminen ja keittiönäyttö. TypeScriptillä ja Reactilla Supabasen ja Cloudflaren päällä, ja Stripe Connect Expressillä ravintolat saavat maksut suoraan — ALV-kuitit ja hyvitykset hoituvat automaattisesti.",
  "code.tapli.3": "Kiinnostavimmat ongelmat ovat tuontipuolella: tekoäly lukee verkkosivun osoitteen, PDF:n tai valokuvan paperimenusta ja poimii jokaisen annoksen, hinnan ja kategorian sekunneissa, merkitsee kaikki 14 EU-allergeenia ja kääntää koko menun yli 20 kielelle yhdellä klikkauksella.",
  "code.perch.1": "Natiivi macOS-valikkorivin työkalu, joka yhdistää ikkunoiden asettelun, kuvakaappaustyökalun, Alt-Tab-ikkunanvaihtajan, leikepöytähistorian, järjestelmän seurannan, levyn ja näytön puhdistuksen, valvetilaistunnot sekä näyttökohtaisen kirkkaudensäädön — ne asiat joihin aiemmin asensin kuusi eri sovellusta.",
  "code.perch.2": "Kirjoitettu Swiftillä ja rakennettu ilman Xcodea: SwiftPM, <code>lipo</code> universaaliin binääriin, ja itsetestit jotka elävät julkaistun binäärin sisällä. Päivittää itsensä paikallaan ja hylkää jokaisen version jota ei ole allekirjoitettu samalla avaimella kuin ajossa oleva.",
  "code.kuori.1": "Tiedostomuunnin Macille, joka tulee luoksesi: pidä Shift pohjassa, raahaa tiedosto Finderistä, ja ruudun keskelle ilmestyy pyörä kaikista muodoista joiksi se taipuu — päästä irti lohkon päälle ja muunnos on tehty. Kuvat, ääni, video, dokumentit ja arkistot, sekä samaan muotoon jäävät työkalut: koon muutos, rajaus, pakkaus, leikkaus, metatietojen poisto, OCR haettavaksi PDF:ksi ja taustan poisto. Kaikki ajetaan laitteella.",
  "code.kuori.2": "Swift ja AppKit, rakennettu ilman Xcodea kuten Perch: SwiftPM, itsetestit julkaistun binäärin sisällä, ad-hoc-allekirjoitettu. Yksi kyvykkyysgraafi pyörittää valintapyörää, <code>kuori</code>-komentorivityökalua, tallennettuja esiasetuksia, monivaiheisia reseptejä ja seurattavia kansioita. Suurin osa on natiivia — ImageIO, PDFKit ja Vision — ja ne muutamat sallivasti lisensoidut apuohjelmat, joita tarvitaan, on niputettu sovellukseen itse kirjoittamallani dylib-uudelleensijoitusskriptillä, joten se toimii ilman mitään <code>PATH</code>:ssa.",
  "code.transcriber.1": "Liitä TikTok-, Reels- tai YouTube-linkki ja saat litteroinnin takaisin — koko videon tai minkä tahansa osan siitä, aikaleimoilla tai ilman. Kaikki ajetaan paikallisesti: <code>yt-dlp</code> hakee äänen, Whisper litteroi sen, eikä mitään lähetetä ulkopuolelle.",
  "code.transcriber.2": "Python, jossa yksi yhteinen ydin palvelee sekä komentorivityökalua että pientä Flask-käyttöliittymää, joka tuo jokaisen rivin näkyviin heti kun se tunnistetaan. Toimii 1,8-kertaisella reaaliaikanopeudella M4:llä ja vie tekstin joko puhtaana tekstinä tai SRT-tekstityksinä. Käytän sitä puhelimesta Tailscalen yli, joten konetta ei tarvitse avata internetiin.",

  "about.1": "Olen Ishan. Perustin Taplin, QR-tilaamisen, joka on käytössä suomalaisravintoloissa joka päivä. Vastaan myynnistä ja markkinoinnista, päätän hinnoittelun ja rakennan tuotteen.",
  "about.2": "Ennen Taplia editoin lyhytvideoita brändeille kolme vuotta, suoritin varusmiespalveluksen kersanttina ja tein ovelta ovelle -myyntiä. Hoidan yhä suurimman osan Taplin käyttöönotoista itse, ja opiskelen tieto- ja viestintätekniikkaa Turun AMK:ssa.",

  "lang.en": "englanti — erinomainen",
  "lang.fi": "suomi — hyvä",
  "lang.hi": "hindi — äidinkieli",
  "lang.mwr": "marwari — äidinkieli",
  "lang.sv": "ruotsi — alkeet",

  "cv.skills": "Osaaminen",
  "sk.build.h": "Kehitys",
  "sk.build.p": "Python, TypeScript, React, HTML/CSS ja SQL päivittäin; jonkin verran Swiftiä.",
  "sk.ai.h": "Tekoälyavusteinen kehitys",
  "sk.ai.p": "Rakennan, suunnittelen ja julkaisen tuotanto-ominaisuuksia pääosin tekoälytyökalujen avulla ja tarkistan työn niiden kanssa.",
  "sk.plat.h": "Alustat ja työkalut",
  "sk.plat.p": "Supabase (PostgreSQL), Cloudflare Pages, Vercel, Stripe Connect, Git ja GitHub, Node.js, PostHog-analytiikka.",
  "sk.sales.h": "Myynti ja kasvu",
  "sk.sales.p": "B2B SaaS -go-to-market alusta loppuun: outbound, demot, hinnoittelu ja käyttöönotto. Jokaisen Taplin ravintolan olen itse myynyt ja ottanut käyttöön, ja tuotesuunnitelma tulee suoraan noista tapaamisista.",
  "sk.creative.h": "Luova työ",
  "sk.creative.p": "Lyhytvideosisältöä ja somea — kolme vuotta brändeille. Premiere Pro, Photoshop, Illustrator, Canva.",

  "cv.experience": "Työkokemus",
  "cv.alongside": "Samaan aikaan",
  "cv.earlier": "Aiemmin",
  "cv.education": "Koulutus",
  "cv.certs": "Sertifikaatit",

  "cv.tapli.h": "Perustaja &amp; toimitusjohtaja — Tapli",
  "cv.tapli": "Perustin ja johdan QR-tilaus- ja digitaalisen ruokalistan alustaa, joka on käytössä suomalaisravintoloissa. Vastaan myynnistä, hinnoittelusta, markkinoinnista ja tuotesuunnasta — ja rakennan ja julkaisen tuotteen itse TypeScriptillä ja Reactilla Supabasen ja Cloudflaren päällä.",
  "cv.clasturku.h": "Myyjä — Clas Ohlson",
  "cv.clas.turku": "Takaisin myymälätyössä Turun myymälässä muutettuani sinne opiskelemaan — hyllytystä, hinnoittelua, kausiesillepanoa ja asiakaspalvelua.",
  "cv.addnow.h": "Markkinointi- ja somevastaava — AddNow",
  "cv.addnow": "Vastaan markkinoinnista ja sisällöstä tekoälypohjaisessa kontaktinhallintasovelluksessa. TikTok- ja Reels-käsikirjoitukset, karusellit, sisältökalenterit ja luova suunta.",
  "cv.helena.h": "Tapahtuma- ja asiakastyö — Helena Riihitupa Oy",
  "cv.helena": "Asiakaskohtaamisia ja tapahtumatyötä Helsingissä. Brändien edustamista suoraan kuluttajille.",
  "cv.clas.h": "Myyjä — Clas Ohlson",
  "cv.clas": "Myymälätyö, esillepano ja tilausten käsittely Suomen ainoassa Clas Ohlsonin verkkokauppavarastossa. Club Clas -lähettiläänä seurasin ja kasvatin kanta-asiakkuuksia.",
  "cv.freelance.h": "Freelance — sosiaalinen media ja videoeditointi",
  "cv.freelance": "Toteutin lyhytvideosisältöä brändeille alusta loppuun — käsikirjoitus, kuvaus, editointi ja tulosten analysointi — TikTokiin, Instagram Reelsiin, YouTube Shortsiin ja LinkedIniin, sekä podcast-editointia ja täyttä tuotantoa.",
  "cv.freelance.clients": "Asiakkaita mm. Moov Kids, Birkkalan Tila, Euro Scalers, The F-Company, Studio Manu ja Ome Energy by Hartwall.",
  "cv.fdf.h": "Kersantti — Puolustusvoimat",
  "cv.fdf": "Vuosi varusmiespalvelusta Upinniemen merivoimien tukikohdassa. Aliupseerikurssi, sen jälkeen toimistoaliupseeri vastuussa yksikön dokumentaatiosta ja hallinnosta.",
  "cv.euro.h": "Somemarkkinoija — Euro Scalers",
  "cv.euro": "Lyhytvideoita ja somemarkkinointia. CapCut, Premiere Pro, Photoshop, Illustrator, Canva.",
  "cv.nordic.h": "Myyntikonsultti — Nordic Sales Crew Oy",
  "cv.nordic": "Kasvokkaista myyntiä yhdessä Suomen suurimmista kenttämyyntitoimistoista. Vastaväitteiden käsittelyä ja asiakasviestintää.",

  "edu.turku.h": "Insinööri (AMK), tieto- ja viestintätekniikka",
  "edu.turku.p": "Turun ammattikorkeakoulu",
  "edu.tampere.h": "Ohjelmistotekniikka, avoimen yliopiston väylä (20 op)",
  "edu.tampere.p": "Tampereen yliopisto",
  "edu.hs.h": "Ylioppilastutkinto",
  "edu.hs.p": "Vuosaaren lukio — opintoja Pythonista ja HTML:stä",

  "mk.intro": "Kolme vuotta sisältöä ja somea ennen kuin aloin rakentaa tuotteita — lyhytvideoita, B2B-videoita ja käsikirjoitettuja case-videoita, ensimmäisestä rungosta lukujen lukemiseen asti.",
  "mk.formats": "Työn muodot: lyhytvideokoukut, B2B-selittäjävideot ja tuotedemot, käsikirjoitetut asiakas-case-videot, build-in-public-sarjat, podcast-editointi ja koko tuotanto briiffistä valmiiseen leikkaukseen.",
  "mk.addnow": "Markkinointijohtaja tekoälypohjaisessa kontaktinhallintasovelluksessa. Tuotteen ominaisuuksien muuttamista sisällöksi jota ihmiset oikeasti katsovat: lyhyet koukut, build-in-public-videot ja opettavat julkaisut jotka tuovat latauksia.",
  "mk.free.h": "Freelance — sosiaalinen media ja videoeditointi",
  "mk.free.p1": "Kolme vuotta koko tuotantoketjua brändeille: käsikirjoitus, kuvaus, editointi ja lukujen lukeminen jälkikäteen. Lyhytvideoita TikTokiin, Instagram Reelsiin, YouTube Shortsiin ja LinkedIniin; B2B-selittäjävideoita ja käsikirjoitettuja asiakas-case-videoita; sekä podcast-editointia ja tuotantoa alusta loppuun.",
  "mk.free.p2": "Ruoan, juoman, energian, maatalouden ja startupien parissa — kuusi asiakasta joiden yleisöillä ei ollut juuri mitään yhteistä, ja juuri se opetti eniten.",
  "fcompany.by": "Precisin ostama",
  "mk.clients": "Editoinut näille",
  "mk.elisa": "Vastasin kansainvälisestä ja alueellisesta somesta (Twitter, Instagram, Twitch) livenä turnauksen aikana.",
  "mk.india": "Kuvasin ja editoin tapahtumasisältöä, mukaan lukien haastattelut Intian Suomen-suurlähettilään ja Maahanmuuttoviraston johtajan kanssa. Somemateriaalia ja verkkosivumuokkauksia.",
  "mk.slush.h": "Slush — media-alue",
  "mk.slush.p": "Tuin podcast-tiimejä, sisällöntekijöitä ja vieraita media-alueella sekä koordinoin haastatteluja. Aiemmin badge-tulostustuotantoa kahden päivän suuren volyymin työnkulussa.",
  "mk.coffee": "Valokuvausta ja videota someen Helsinki Coffee Festivalilla sekä Jäätelö- ja Suklaakarnevaaleilla.",

  "co.1": "SaaS-tuote QR-tilaamiseen ravintoloissa, tuotannossa Suomessa ja päivittäisessä käytössä oikeilla tilauksilla. Useimmat ravintolat ovat käytössä alle 30 minuutissa.",
  "co.2": "Asiakas skannaa tarran tai lasinalusen pöydässä, tai valitsee pöytänsä pohjapiirroksesta. Hän tilaa ja maksaa puhelimellaan — Apple Pay, Google Pay, MobilePay tai kortti — ja tilaus ilmestyy keittiön näytölle välittömästi, ohjattuna oikealle asemalle. Ei sovellusta eikä odottelua tarjoilijan katseen saamiseksi.",
  "co.3": "Käyttöönotto on se osa jota ravintolat pelkäävät. Liitä verkkosivusi osoite, lataa PDF tai valokuvaa paperimenusi, niin tekoäly poimii jokaisen tuotteen, hinnan ja kategorian sekunneissa. Tarkistat kaiken ennen tallennusta. Kaikki 14 EU-allergeenia merkitään, asiakkaat suodattavat reaaliajassa, ja yksi klikkaus kääntää koko menun yli 20 kielelle.",
  "co.4": "Menun lisäksi: päivän tarjoukset jotka vanhenevat itsestään, tilausten seuranta reaaliajassa, skannaus- ja hakuanalytiikka CSV-vientinä, brändinmukainen ulkoasu esikatselulla, ja tekoälyn luonnostelemat vastaukset Google-arvosteluihin. Toimii myös ruokarekoille, festivaalikojuille ja hotelleille — huonepalvelu, baari ja spa saman QR-koodin takana.",
  "co.5": "Perustin Taplin ja pyöritän sitä päivittäin. Myynti, markkinointi, kasvu, hinnoittelu, ja yhdessä CTO:n kanssa päätökset siitä mitä rakennamme ja mitä jätämme tekemättä. Ravintolat pyytävät sinulta kaikkea, ja suurin osa työstä on sen selvittämistä mikä siitä oikeasti liikuttaa liiketoimintaa. Otan yhä useimmat asiakkaat käyttöön itse, ja sieltä tuotesuunnitelma tulee."
};
